### ISSUE TITLE
Add weights textfile into props file.

### ISSUE THREAD

**Issue by HenryGeorgist** [HydrologicEngineeringCenter/ConfidenceBuilderPlugin#5]
Currently the weights text file is in the shared directory, but the properties for the study are in the properties file.

refactor to have all properties in the same file.
Consider adding a class to the project for properties so that the complexity of properties can be separated from the computation of confidence intervals and line simplification.

**Comment by Brennan1994** [comment]
@HenryGeorgist can you add a weights file to the repo I can use to test against?

**Comment by HenryGeorgist** [comment]
This is the one i was using for Ala-Wai. It has each lifecycle equally weighted. there should be one in the shared directory of the trinity model as well, it will have different weight values.  The text file name is binweights_by_lifecycle.txt

below,0.000000000000000
LC1,0.1
LC2,0.1
LC3,0.1
LC4,0.1
LC5,0.1
LC6,0.1
LC7,0.1
LC8,0.1
LC9,0.1
LC10,0.1
above,0.000000000000000
