### ISSUE TITLE
Add Continuous Integration Continuous Delivery

### ISSUE THREAD

**Issue by HenryGeorgist** [HydrologicEngineeringCenter/ConfidenceBuilderPlugin#6]
We can either use team city or we can use github actions. Either works for me.

**Comment by Brennan1994** [comment]
Done. Using team city,

Currently publishing to the Maven Snapshot repository on nexus: https://www.hec.usace.army.mil/nexus/repository/maven-snapshots/mil/army/usace/hec/ConfidenceBuilderPlugin/1.0-SNAPSHOT/ConfidenceBuilderPlugin-1.0-20201203.024050-1.jar
